### ISSUE TITLE
Add multiple layouts

### ISSUE THREAD

**Issue by d-siganos** [realtimecoded/realtimeCoded#11]
**Feature**
We would like the user interface to feature multiple layouts in addition to the current one

**Additional context**
We have tried to switch to a horizontal split as I have seen in multiple websites, but it wouldn't work. We believe it is because we are using the Bootstrap `col` class as well as the split pane.

- BonfireScratch
  - Owner of the Padscape organization

**Comment by d-siganos** [comment]
@SimpleBinary could you help me with this? I would appreciate your help.

**Comment by plastictortoise** [comment]
@BonfireScratch What do you mean by "our previous attempts failed"?

You could have a few layouts (eg. `3`) and then set a Local storage variable to `1`, `2` or `3`.

I also recommend setting the dark theme as default and adding a line number on/off option.

**Comment by d-siganos** [comment]
@SimpleBinary I have tried to switch to a horizontal split as I have seen in multiple websites, but it wouldn't work. I believe it is because I am using the bootstrap `col` class. However I haven't tackled this issue for quite long and may be wrong.

**Comment by d-siganos** [comment]
As for the line numbers, I am not sure how to do that either but I might at some stage

**Comment by d-siganos** [comment]
I have been thinking of a theme editor, and I expect it to be a very nice feature

**Comment by d-siganos** [comment]
@SimpleBinary this issue is going to be fixed tomorrow

**Comment by d-siganos** [comment]
@SimpleBinary issue fixed.

**Comment by d-siganos** [comment]
@SimpleBinary line numbers have also been implemented.
