### ISSUE TITLE
Code seems screwed when typing long lines

### ISSUE THREAD

**Issue by d-siganos** [realtimecoded/realtimeCoded#3]
**Describe the bug**
The code seems screwed when the textarea scrolls.

**To Reproduce**
1. Go to [the web host](https://realtimecoded.github.io/realtimeCoded/)
2. Press keys continuously to automatically scroll down the textarea
3. See the result

**Expected behavior**
The expected behavior is to have all the widgets in one place

**Desktop:**
 - OS: Any (seen with Windows 7, Windows 10, iOS, Android and Ubuntu)
 - Browser: Any (seen with Chrome, MSIE, and Safari)
 - Version: Any

**Comment by d-siganos** [comment]
I think the problem is in both the CSS and the JavaScript

**Comment by d-siganos** [comment]
@Dandigit could you help me with this? I am stuck...

**Comment by Dandigit** [comment]
@BonfireScratch I'll take a look

**Comment by d-siganos** [comment]
@Dandigit no worries, I fixed that
