### ISSUE TITLE
No proper error handling

### ISSUE THREAD

**Issue by d-siganos** [realtimecoded/realtimeCoded#7]
**Describe the bug**
When a user writes invalid code, the error message is not displayed

**To Reproduce**
1. Write some invalid JavaScript code
2. See the result 

**Expected behavior**
If possible, I would like it to display the error information

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
Notify @SimpleBinary

**Comment by plastictortoise** [comment]
@BonfireScratch Could you give me an examlpe of where this does not work, because using this code sample,  I get an error in the browser console:

```html
<script>
    e
</script>
```
In the console it says that `e` is not defined

**Comment by d-siganos** [comment]
@SimpleBinary. It seems like I wasn't  clear, I would like the error to be displayed on the result iFrame

**Comment by plastictortoise** [comment]
@BonfireScratch Well, you could check the code before adding it to the iframe and if there is an error, you could use some other html code, but that is not very javascripty. What you currently have is what an actual website would display if you had an error. Nothing.

**Comment by d-siganos** [comment]
@SimpleBinary I do not really care about how JavaScripty it is, but I have noticed that jsfiddle and the w3schools online editor don't have this feature. I have already tried detecting the error message directly, but that failed. Do you think it is an important, or is it insignificant?

**Comment by plastictortoise** [comment]
@BonfireScratch I think someone should realise that something is not right when what they were trying to do didn't work and would go back over their code anyway.

**Comment by d-siganos** [comment]
@SimpleBinary @Dandigit how do I set up a database for this website? I prefer it not to have Node dependencies. If I need a server, what properties should the server have?

**Comment by Dandigit** [comment]
@BonfireScratch How do you intend to use this database?

If you want to use it to store user accounts, then you'll most certainly need a server as well, as there's a lot more to a login systen than just data storage. Think logic, interfacing, encryption, etc.

You don't need to write the code for the backend in Node - almost every general purpose language has a web framework/web frameworks written for it. Node is a good option, though, as it's fast, simple and has an abundance of available libraries.

As far as servers go, it's up to you. Depending on which platform you end up developing on (Node, Django, PHP, etc.) different options from different providers will suit, or a general purpose option will work with any platform.

**Comment by d-siganos** [comment]
@Dandigit well, I intend to use the database in order to store users' code (and user accounts?), so that people can save their edits in plain text files. I have a Raspberry Pi server, but I have no idea how to use it. I have considered using `PouchDB`, which has no Node dependencies, or else I plan on using PHP or `MongoDB`. Does the server need to have a DNS provider to be accessed by the website? If so, then I am most certainly not able to pay for that.

**Comment by Dandigit** [comment]
@BonfireScratch MongoDB is not a programming environment. Databases are not programming environments. Web server programs (like a Node/PHP script) query database programs (like MongoDB/SQLite/Postgres to read and write data. The databases don't execute logic by themselves.

Remember that a server is just a computer. Other computers will need some way to access your server (the Raspberry Pi). You'll need to obtain a publicly accessible IP address through port forwarding, and then you can use that with a domain. Otherwise, there's no way for someone who's not on your local network to type in an address and access your site.

The reason I suggest using a hosting provider is because most home internet plans prohibit running a public web server - you'd likely need to switch to a business plan, and the incurred cost from this would likely be far greater than the $5-10 a month it costs for a simple DigitalOcean server.

**Comment by d-siganos** [comment]
@Dandigit I also think it is cheaper to only buy a domain than registering to DigitalOcean. Just one more question, though, is there a way in which you can make your own DNS provider and pay less?

**Comment by Dandigit** [comment]
@BonfireScratch You can't only buy a domain - buying a domain is just like buying a parcel of land. You have the land, but there's nothing on it without a server.

In theory, you can create your own DNS provider, but you won't be paying less. Creating a DNS provider wouldn't solve the issue, anyway. What you need is a publicly accessible server, not a 'DNS provider'.

**Comment by d-siganos** [comment]
@Dandigit then, what is the use of making a DNS provider?

**Comment by Dandigit** [comment]
@BonfireScratch There's no point, unless you're concerned about \<insert ISP\>/Google/Cloudflare/\<any other common DNS provider\> taking your private data.

**Comment by d-siganos** [comment]
@Dandigit I am not concerned about this issue. I don't have any more questions, for now, thank you!

**Comment by d-siganos** [comment]
@Dandigit in case the server is out of power, is connecting it to the UPS a decent solution?

**Comment by Dandigit** [comment]
@BonfireScratch Connecting it to a UPS is a good idea, yes.
